apiVersion: v1
kind: Pod
metadata:
  name: builder
spec:
  containers:
  - image: quay.io/jfclere/tomcat10-buildah
    name: war
    volumeMounts:
    - mountPath: /auth
      name: app-volume
      readOnly: true
  serviceAccountName: builder
  volumes:
  - name: app-volume
    secret:
      secretName: jfc
