FROM jfclere/tomcat-in-the-cloud
LABEL Description="Tomcat image with a demo webapp"
VOLUME /tmp

USER root

ARG war
RUN echo $war
ADD $war/ /apache-tomcat/webapps

WORKDIR /apache-tomcat

ARG registry_id
ENV OPENSHIFT_KUBE_PING_NAMESPACE $registry_id

RUN sh -c 'chmod a+x bin/*.sh'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "bin/startup.sh" ]
