FROM jfclere/tomcat-stuffed
LABEL Description="Tomcat image with a demo webapp"
VOLUME /tmp

USER root

ARG war
RUN echo $war
ADD $war/ /apache-tomcat/webapps

WORKDIR /apache-tomcat

ENV OPENSHIFT_KUBE_PING_NAMESPACE "default"

RUN sh -c 'chmod a+x bin/*.sh'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "bin/startup.sh" ]
