ARG IMAGE
FROM ${IMAGE}
LABEL Description="Tomcat image to use with the JWS operator"
VOLUME /tmp

USER root

ADD server.xml.stuffed /deployments/conf/server.xml
ADD start.sh /opt
ADD usekube.sh /opt
ADD usedns.sh /opt
RUN chmod 777 /opt/*.sh

ARG war
RUN echo $war
ADD $war /deployments

ENV KUBERNETES_NAMESPACE "default"

ENV JAVA_OPTS=""

ENV ENV_FILES=""

ENTRYPOINT [ "/opt/start.sh" ]
