apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /myhome
    server: 172.30.194.91
  persistentVolumeReclaimPolicy: Retain 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
spec:
  volumeName: pv0001
  storageClassName: ""
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
