apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tomcat
  annotations:
    openshift.io/display-name: tomcat
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/jfclere/tomcat10.1-demo:latest
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
