kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-for-tomcat
  labels:
    app: tomcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
  volumeMode: Filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nfs
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: quay.io/jfclere/nfs
        ports:
        - name: nfs
          containerPort: 2049
        volumeMounts:
        - mountPath: /myhome
          name: nfs-for-tomcat
      volumes:
        - name: nfs-for-tomcat
          persistentVolumeClaim:
            claimName: nfs-for-tomcat

---

kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ClusterIP: "None"
  ports:
    - name: nfs
      port: 2049
      targetport: "2049"
  selector:
   app: tomcat

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.30.127.58
    path: "/myhome"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  #  - ReadWriteMany
  # storageClassName: ""
  resources:
    requests:
      storage: 10Mi
