apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  # namespace: tomcat-in-the-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  # namespace: tomcat-in-the-cloud
