kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-jws
allowedCapabilities:
- SETUID
- SETGID
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
allowHostNetwork: false
allowHostPID: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
