apiVersion: v1
kind: Service
metadata:
  name: my-tomcat-svc
  labels:
    app: tomcat
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tomcat
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: quay.io/jfclere/tomcat10.1-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
