apiVersion: v1
kind: DeploymentConfig
metadata:
  name: tomcat-buildconfig
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tomcat-buildconfig
    spec:
      containers:
        - name: my-image
          image: origin-tomcat-sample:latest
